// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_gemma_chat/data/models/chat_message.dart';
import 'package:flutter_gemma_chat/data/models/chat_thread.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChatMessageAdapter());
    registerAdapter(ChatThreadAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChatMessageAdapter());
    registerAdapter(ChatThreadAdapter());
  }
}
